### ISSUE TITLE
Please rename primary branch to `main`

### ISSUE THREAD

**Issue by nyurik** [thomasarmel/socket-server-mocker#19]
`main` has became the default primary branch, and for many English speakers it is not as offensive.  I believe it is always good to offend as few people as possible, and this is an easy thing to do. See articles like [this one](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main) and [this one](https://github.com/github/renaming) explaining the move.

The actual steps are [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

**Comment by thomasarmel** [comment]
Now attending EuroRust, I'll do it soon after 😄

**Comment by thomasarmel** [comment]
Ok done
